/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_laka_live_libyuv_LibYuv */

#ifndef _Included_com_laka_live_libyuv_LibYuv
#define _Included_com_laka_live_libyuv_LibYuv
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_laka_live_libyuv_LibYuv
 * Method:    convertNV21ToARGB
 * Signature: ([B[BII)V
 */
JNIEXPORT void JNICALL Java_com_laka_live_libyuv_LibYuv_convertNV21ToARGB
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_laka_live_libyuv_LibYuv
 * Method:    convertARGBToNV21
 * Signature: ([B[BII)V
 */
JNIEXPORT void JNICALL Java_com_laka_live_libyuv_LibYuv_convertARGBToNV21
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_laka_live_libyuv_LibYuv
 * Method:    ARGBMirror
 * Signature: ([B[BII)V
 */
JNIEXPORT void JNICALL Java_com_laka_live_libyuv_LibYuv_ARGBMirror
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_laka_live_libyuv_LibYuv
 * Method:    ARGBRotate
 * Signature: ([B[BII)V
 */
JNIEXPORT void JNICALL Java_com_laka_live_libyuv_LibYuv_ARGBRotate
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
