package laka.live.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import laka.live.bean.ChatMsg;
import laka.live.bean.ChatSession;
import laka.live.bean.MusicInfo;

import laka.live.dao.ChatMsgDao;
import laka.live.dao.ChatSessionDao;
import laka.live.dao.MusicInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig chatMsgDaoConfig;
    private final DaoConfig chatSessionDaoConfig;
    private final DaoConfig musicInfoDaoConfig;

    private final ChatMsgDao chatMsgDao;
    private final ChatSessionDao chatSessionDao;
    private final MusicInfoDao musicInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        chatMsgDaoConfig = daoConfigMap.get(ChatMsgDao.class).clone();
        chatMsgDaoConfig.initIdentityScope(type);

        chatSessionDaoConfig = daoConfigMap.get(ChatSessionDao.class).clone();
        chatSessionDaoConfig.initIdentityScope(type);

        musicInfoDaoConfig = daoConfigMap.get(MusicInfoDao.class).clone();
        musicInfoDaoConfig.initIdentityScope(type);

        chatMsgDao = new ChatMsgDao(chatMsgDaoConfig, this);
        chatSessionDao = new ChatSessionDao(chatSessionDaoConfig, this);
        musicInfoDao = new MusicInfoDao(musicInfoDaoConfig, this);

        registerDao(ChatMsg.class, chatMsgDao);
        registerDao(ChatSession.class, chatSessionDao);
        registerDao(MusicInfo.class, musicInfoDao);
    }
    
    public void clear() {
        chatMsgDaoConfig.clearIdentityScope();
        chatSessionDaoConfig.clearIdentityScope();
        musicInfoDaoConfig.clearIdentityScope();
    }

    public ChatMsgDao getChatMsgDao() {
        return chatMsgDao;
    }

    public ChatSessionDao getChatSessionDao() {
        return chatSessionDao;
    }

    public MusicInfoDao getMusicInfoDao() {
        return musicInfoDao;
    }

}
