/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/*
 * Class:     com_laka_live_audio_Mverb
 * Method:    getTestString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_laka_live_audio_Mverb_getTestString(JNIEnv *env, jobject obj){
    return (*env)->NewStringUTF(env,"This just a test for Android Studio NDK JNI developer!");
}


